# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "logicmlbot.policies.logicmlbot_policy.LogicMlBotPolicy"
  - name: KerasPolicy
  - name: MappingPolicy
