model_dir: run-logic-eng

data:
  train_features_file: logic-train.txt
  train_labels_file: english-train.txt
  eval_features_file: logic-val.txt
  eval_labels_file: english-val.txt
  source_words_vocabulary: logic-vocab.txt
  target_words_vocabulary: english-vocab.txt

eval:
  eval_delay: 1800  # Every 30 min

train:
  batch_size: 8